# see https://starship.rs/config/

add_newline = false

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
disabled = true

[character]
success_symbol = "[❯](bold red)[❯](bold yellow)[❯](bold green)"
error_symbol   = "[❯❯❯](bold bright-red)"
vicmd_symbol   = "[:](bold red)[:](bold yellow)[:](bold green)"

[cmd_duration]
min_time = 5000
format = "⏱ [$duration]($style) "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format="[$symbol$branch]($style) "

[git_status]
format='([$all_status$ahead_behind]($style) )'
modified='•'

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
format = "${symbol}[${version}]($style) "
symbol = " "
style = "bright-purple"

[julia]
symbol = " "

[line_break]
disabled = true

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
disabled = true

[shlvl]
symbol = "↕️ "
disabled = false

[swift]
symbol = "ﯣ "
